### ISSUE TITLE
Implement Stack-Creation functionality

### ISSUE THREAD

**Issue by devosray** [TripleParity/docks-api#19]
Create an endpoint on the Docks api that will deploy a docker-compose file.

**Comment by egeldenhuys** [comment]
- [ ] The Docker CLI needs to be wrapped so that we can execute the stack commands
- [ ] An API spec needs to be created for deploying a stack
- [ ] The API spec needs to be implemented

**Comment by egeldenhuys** [comment]
Closed by PR
