### ISSUE TITLE
JWT Auth

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/docks-api#29]
Research and implement JWT. Until the database is integrated mock values/tests can be used.

**Comment by annamarieHelberg** [comment]
Hi guys. How is the Authentication looking? We need to get the login page up and running so we need your work as soon as possible please.

**Comment by CDuPlooy** [comment]
Thank you @annamarieHelberg @egeldenhuys . 

I won't have too much time to work on this so I'm hoping adding it to the front end doesn't cause problems. I'll let everyone know if we struggle. :paintbrush:

**Comment by egeldenhuys** [comment]
How does this look for now? I will implement it with some tests to verify the workings

### POST `/auth/token`
#### Request Body
```json
{
  "username": "<username>",
  "password": "<password>"
}
```

#### Response
##### 200 Authentication Successful
```json
{
  "jwt": "<jwt>"
}
```
##### 401 Bad Credentials

**Comment by egeldenhuys** [comment]
> Whenever the user wants to access a protected route or resource, the user agent should send the JWT, typically in the Authorization header using the Bearer schema. The content of the header should look like the following:
> 
> `Authorization: Bearer <token>`
> 
> This is a stateless authentication mechanism as the user state is never saved in server memory. The server's protected routes will check for a valid JWT in the Authorization header, and if it's present, the user will be allowed to access protected resources. As JWTs are self-contained, all the necessary information is there, reducing the need to query the database multiple times.
- https://jwt.io/introduction/

**Comment by CDuPlooy** [comment]
This looks great! Thanks @egeldenhuys

**Comment by egeldenhuys** [comment]
##### TODO
- [ ] Query the database when checking credentials instead of mock `admin/admin`

**Comment by egeldenhuys** [comment]
The database has been integrated in my branch. Will create a PR when suitable.

**Comment by egeldenhuys** [comment]
This has been implemented in master
