### ISSUE TITLE
docker-compose up port issue

### ISSUE THREAD

**Issue by annamarieHelberg** [TripleParity/docks-api#55]
I experience an error every time I try to run docker-compose up for the second time. It tells me the port is already in use even after the 'docker-compose down' command which leads to me having to kill the process on the port before I can continue. 

Is it a mistake on my side or can it be fixed on the api side?

**Comment by egeldenhuys** [comment]
It might take a while for `docker-compose` to kill the running containers.

I recommend using `docker stack` to deploy a specific version of `docks-api` and then using `ng serve` to host the front-end. `docker-compose` does not support Docker Swarm.
See the [README](https://github.com/TripleParity/docks-ui/tree/develop#serving-docks-ui-using-angular-cli) in docks-ui develop.

Let me know if you have further problems with this

**Comment by annamarieHelberg** [comment]
I will try that in the future. Can you please update it in the docks-api README as well?

**Comment by egeldenhuys** [comment]
I will document the workflows as part of #56
