### ISSUE TITLE
Reduce size of Docker image

### ISSUE THREAD

**Issue by devosray** [TripleParity/docks-api#65]
Currently, the size of the final Docks API docker image well exceeds 100MB compressed and even larger locally:

![image](https://user-images.githubusercontent.com/5329962/43084016-2112df04-8e98-11e8-85ad-7e41c4342cdf.png)

![image](https://user-images.githubusercontent.com/5329962/43084064-3a1999ac-8e98-11e8-8f83-150c1834f495.png)

This is in stark contrast to the Docks UI image:

![image](https://user-images.githubusercontent.com/5329962/43084113-527b3b0e-8e98-11e8-9ab6-bb4223be36e5.png)

![image](https://user-images.githubusercontent.com/5329962/43084135-5e69d27c-8e98-11e8-96c4-5be88a426cdd.png)

This issue will investigate the size disparity and possible solutions.

**Comment by egeldenhuys** [comment]
Multistage builds might also be related - #32
